name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        pytest-version: ["8.0", "8.3"]
        exclude:
          # Reduce matrix size for efficiency
          - os: windows-latest
            python-version: "3.10"
          - os: macos-latest
            python-version: "3.10"
          # Exclude Python 3.13 with pytest 8.0 due to AST compatibility issues
          - python-version: "3.13"
            pytest-version: "8.0"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install dependencies
      run: |
        uv python install ${{ matrix.python-version }}
        uv sync --all-extras --dev
        uv add pytest==${{ matrix.pytest-version }}

    - name: Run tests
      run: |
        uv run pytest tests/ -v

    - name: Run linting
      run: |
        uv run ruff check src/
        uv run mypy src/

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Build package
      run: |
        python -m pip install --upgrade pip build
        python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}